# GPUS: (0,1,2,3)
# WORKERS: 4
# PRINT_FREQ: 1

DDP_TRAIN: FALSE

DATASET:
  DATASET_NAME: CIFAR10
  ROOT: "../datasets"
  ROOT_FOLDER: "./datasets/Cifar10"
  TRAIN_FOLDER: "./datasets/train"
  TEST_FOLDER: "./datasets/test"
  ZIP_FOLDER: "./datasets/Cifar10.zip"
  SELECTION_RATIO: 1
  SPLIT_RATIO: 0.7

DATASET_EXTRACT:
  DATASET_INFO: "../Info.csv"
  ZIP_FILE_PATH: "../Dataset/áº¢nh"
  EXTRACT_PATH: "../DTLHerb"
  MIN_IMG: 100
  MAX_IMG: 9999

TRAIN:
  DATA:
    IMAGE_SIZE: [256, 256]
    BATCH_SIZE: 64
    SHUFFLE: True
    MEAN: [0.48667304, 0.47782094, 0.44596779]
    STD: [0.20571293, 0.20116103, 0.20227837]
  TRAIN_PARA:
    MODEL_TYPE: 1 #{1: Resnet50, 2: DenseNet201, 3: VGG19, 4: ConvNeXt_Large, 5: MobileNet}
    BEGIN_EPOCH: 0
    END_EPOCH: 100
    LAST_EPOCH: 0
    OPTIMIZER: "AdamW"
    RESUME: False
  OPTIONAL:
    SAVE_CHECKPOINT: TRUE
    CHECKPOINT_PATH: "./resume_model/checkpoint.pth"
    SAVE_BEST: TRUE
    BEST_PATH: "./best_model/checkpoint.pth"
    SAVE_METRICS: TRUE
    METRICS_PATH: "./metrics/metrics.csv"
  AUG:
    CUTMIX: [TRUE, 0.5]
    MIXUP: [TRUE, 0.5]
    FMIX: [FALSE, 0.5]

TEST:
  BATCH_SIZE: 32

