GPUS: (0,1,2,3)
WORKERS: 4
PRINT_FREQ: 1

DATASET:
  DATASET_NAME: VNHerb-data
  ROOT: "../DTLHerb"
  ROOT_FOLDER: "../DTLHerb"
  TRAIN_FOLDER: "../train"
  TEST_FOLDER: "../test"
  ZIP_FOLDER: "./datasets/Cifar10.zip"
  SELECTION_RATIO: 1
  SPLIT_RATIO: 0.7

DATASET_EXTRACT:
  DATASET_INFO: "./config/Info.csv"
  ZIP_FILE_PATH: "../Dataset/áº¢nh"
  EXTRACT_PATH: "../DTLHerb"
  MIN_IMG: 100
  MAX_IMG: 9999

TRAIN:
  DATA:
    IMAGE_SIZE: [256, 256]
    BATCH_SIZE: 256
    SHUFFLE: True
    # 447
    MEAN: [0.66565923, 0.66174304, 0.57747589] 
    STD: [0.20152938, 0.20600946, 0.209565]
  TRAIN_PARA:
    MODEL_TYPE: 1 #{1: Resnet50, 2: DenseNet201, 3: VGG19, 4: ConvNeXt_Large, 5: MobileNet}
    BEGIN_EPOCH: 0
    END_EPOCH: 50
    LAST_EPOCH: 0
    OPTIMIZER: "AdamW"
    RESUME: False
    EARLY_STOPPING: TRUE
    PATIENCE: 10

  OPTIONAL:
    SAVE_CHECKPOINT: TRUE
    CHECKPOINT_PATH: "./resume_model/checkpoint.pth"
    SAVE_BEST: TRUE
    BEST_PATH: "./best_model/best_checkpoint.pth"
    SAVE_METRICS: TRUE
    METRICS_PATH: "./metrics/metrics.csv"
  AUG:
    CUTMIX: [TRUE, 0.5]
    MIXUP: [TRUE, 0.5]
    FMIX: [TRUE, 0.5]

TEST:
  BATCH_SIZE: 256

